title:   Tran Anh Tuan
logo: /assets/img/avata2.png
description: +84-936-209-136 tuanatran.vn@gmail.com www.linkedin.com/in/tuantran89
##show_downloads: true
theme: jekyll-theme-minimal

linkedin: https://www.linkedin.com/in/tuantran89

